---
name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: just check
      - run: just lint
      - run: just test
      #- run: just test_each_feature
